# General configuration
experiment:
  name: PowerForecasting_STL_VMD
  seed: 42
  device: "cuda"  # "cuda" or "cpu"
  epochs: 30
  batch_size: 64
  learning_rate: 0.001
  early_stopping_patience: 30

# Dataset configuration
data:
  root_path: "data/dataset_Laundry_modified.csv"
  # root_path: "data/dataset_figshare_processed.csv"
  target: "Active_Power" # DKSAC
  # target: "Power (MW)" # figshare
  sequence_length: 48
  prediction_length: 1

# STL decomposition parameters
stl:
  enabled: true
  period: 9 

# VMD decomposition parameters
vmd:
  alpha: 50000     # bandwidth constraint
  tau: 0
  k: 3        # number of modes
  dc: 0
  init: 1
  tol: 1e-7
  lambda_param: 75  # Lagrange multiplier for reconstruction constraint
  enabled: true

# Model configuration
model:
  name: "TimesNet_BiLSTM"
  input_features: 11 
  # input_features: 6 
  output_features: 1

  timesnet:
    d_model: 32
    d_ff: 8
    num_kernels: 9
    num_times_blocks: 2
    top_k: 1
    dropout: 0.1188

  bilstm:
    hidden_size: 32
    layers: 3
    bidirectional: true

# Training options
training:
  optimizer: "adam"
  loss_function: "mse"
  metrics: ["mae", "rmse", "r2"]

  # checkpoint_dir: "outputs/Figshare/models"
  checkpoint_dir: "outputs/Yulara/models"
  
  model_dir: "STL_VMD_TimesNet_BiLSTM"

  save_best_only: true
  verbose: true